### ISSUE TITLE
Bug avec le infinite scroll

### ISSUE THREAD

**Issue by ms-studio** [n3krozoft/n3krozoft.com#10]
Ya un "bug":

- dans "projects", si tu cliques sur "more posts", dans mon chrome ça
foire (les projects plus anciens n'apparaissent pas et une image bizarre
de quartz viens tout en haut). Dans mon iphone, ça marche mais les
projets plus anciens apparaissent avec l'ancienne mise en page (petite
image ovale).

Il faut remonter ça à l'auteur du thème pour voir s'il peut solutionner.

**Comment by ms-studio** [comment]
Hmm, apparemment un ticket est déjà ouvert: https://array.is/support/topic/problems-with-infinite-scroll/

À suivre.

**Comment by mikemcalister** [comment]
Hi Manuel, 
The Infinite Scroll in Jetpack is currently broken and causing issues on many themes. We've reported the issue, but In the mean time, you can download [Jetpack 3.1.1](https://downloads.wordpress.org/plugin/jetpack.3.1.1.zip) to fix the Infinite Scroll issue.

**Comment by ms-studio** [comment]
Hi @mikemcalister , thanks for letting me know about the Jetpack 3.1.1. compatibility!
But I don't like to downgrade the plugin since we're using a few other functions... will rather live for a while without the infinite scroll :)

**Comment by mikemcalister** [comment]
We'll keep an eye on the Jetpack update and release any fixes ASAP if necessary. Thanks for your patience!

**Comment by ms-studio** [comment]
Issue fixed thanks to Designer 1.1.6 update!
