### ISSUE TITLE
Abécédaire

### ISSUE THREAD

**Issue by ms-studio** [n3krozoft/n3krozoft.com#2]
Idée: créer un abécédaire

Il doit exister une ébauche datée de 2004 (balkan promenade)

trouvé dans un courriel, du Fri, 12 Mar 2004

tasted and approved:

10111

a
art-core_link
arteplaya_link
alien 8_link
aloha c:10_link

b
bugtalkzoo_music_link

c
curators_bad smell

d
dragos
doug

e
emawaysh _ ethiopian witch +++

f
fergana_valley in central asia
finnegan's wake_reading

g_goethe die blume  kennt kein warum, sie bluht weil sie bluht

h
hectic_situationism
h3x_see under letter z
hamarstroem_swedish witchcraft
hans schaudi

i

j
jlg
 
k_.kz_kazak interet domain name www.kzrrrzk.kz
klonopin
k_kapital letter
kernel
kantik des kantiks 
karkovski
konstruktivism_realism

l
lol
lisa
léo
letov

m
mira_saw andrei rublev three times

n
nezvanova, netochka_thing
nih-1.60_friendly design device
n3krozoft_machine

o
onyx

p
parlism

q

r
ripper
remor
rosenthal
radiscza
r_reich, wilhelm
rublov, andrei_painter

s
straub-huillet_kino ---
shamiladze, irina_biodivinity
s_switzerland_two thirds of it's territory desertic and unhabitable

t_taty_russian dolls, teenage stardom, +++
turbo folk
tadaslav

u

v
viper
voodoo_jean bertrand aristide

w

x
xipharg

y

z_zohar

**Comment by BorisAladar** [comment]
Too  complicated to make as a project for archives
