### ISSUE TITLE
Web site - structural

### ISSUE THREAD

**Issue by BorisAladar** [n3krozoft/n3krozoft.com#8]
- the "featured image" shouldn't be part of the "gallery"

**Comment by ms-studio** [comment]
If you want to fix this on a post:

- Switch the editor to visual mode. 
- Edit the gallery by clicking on the pen icon.
- This opens the window "Edit gallery", where you can remove the featured image.
- Click the "Update gallery" button.

**Comment by BorisAladar** [comment]
ok
